const data = {
  
  products: [
    {
      id: 1,
      name: 'Toyota Yaris',
      model: 'model 1',
      year: 2000,
      image: '/images/car1.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },
    {
      id: 2,
      name: 'Nissan Sunny',
      model: 'model 1',
      year: 2000,
      image: '/images/car2.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },
    {
      id: 3,
      name: 'Nissan Sunny',
      model: 'model 1',
      year: 2000,
      image: '/images/car3.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },
    {
      id: 4,
      name: 'Nissan Sunny',
      model: 'model 1',
      year: 2000,
      image: '/images/p1.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },
    {
      id: 5,
      name: 'Nissan Sunny',
      model: 'model 1',
      year: 2000,
      image: '/images/p1.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },
    {
      id: 6,
      name: 'Nissan Sunny',
      model: 'model 1',
      year: 2000,
      image: '/images/p1.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },
    {
      id: 7,
      name: 'Nissan Sunny',
      model: 'model 1',
      year: 2000,
      image: '/images/p1.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },
    {
      id: 8,
      name: 'Nissan Sunny',
      model: 'model 1',
      year: 2000,
      image: '/images/p1.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },
    {
      id: 9,
      name: 'Nissan Sunny',
      model: 'model 1',
      year: 2000,
      image: '/images/p1.jpg',
      price: 32000,
      description: ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, fugit omnis? Adipisci quasi illum eligendi? Illo excepturi aspernatur fuga, consequuntur, fugit ipsam commodi quidem ab dolorem cupiditate animi cum unde.',
    },

  ],
};
export default data;
